---
- name: checkout phalcon repository
  git: repo=https://github.com/phalcon/cphalcon.git version=1.3.5 dest=/tmp/cphalcon

- name: build phalcon
  action: command {{ item }} chdir=/tmp/cphalcon/build
  with_items:
    - ./install

- name: copy phalcon.ini
  copy: src=phalcon.ini dest=/etc/php5/mods-available/phalcon.ini owner=root group=root mode=0644

- name: enable phalcon
  action: command {{ item }}
  with_items:
    - php5enmod phalcon
  notify: restart apache
  ignore_errors: True